### ISSUE TITLE
Increase in-line documentation

### ISSUE THREAD

**Issue by eddie-knight** [eddie-knight/starfinder-api#73]
Please comment **here below** with suggestions for areas that could be clarified by in-line comments. Suggestions may come in the form of a question, ie. "What does `some_function` do?"

**Comment by CrossBeaux** [comment]
It would be helpful to explain what each element is in the base route function.
(def base_route(namespace):)

**Comment by eddie-knight** [comment]
`get_item_objects` could be renamed `get_items_as_models`

**Comment by eddie-knight** [comment]
```
category_ids = get_category_ids(category)
where = where_category_ids(category_ids)
```
This^ could become:
```
where = where_category_is(category_ids)
```

**Comment by CrossBeaux** [comment]
Adding comments to init.py would be very be helpful as public_tables is used in the helper.py.
