### ISSUE TITLE
Error when searching by name.

### ISSUE THREAD

**Issue by CrossBeaux** [eddie-knight/starfinder-api#78]
To replicate, go to: http://localhost:5000/api/v1/search/spells/poop/
Results in:
TypeError: __init__() got an unexpected keyword argument 'multi'

File "/code/app.py", line 139, in search
data = Select('*', table, multi=True, name=name, where=where).all()

**Comment by eddie-knight** [comment]
Will work this. Also, the error results regardless of the name being valid or invalid.

**Comment by eddie-knight** [comment]
Resolved this in SFAPI-51
